"""Payment mmodel modification

Revision ID: 1452b2197529
Revises: c7233fdac710
Create Date: 2025-01-02 18:54:55.367235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1452b2197529'
down_revision: Union[str, None] = 'c7233fdac710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_package_payment', sa.Column('payment_gateway', sa.Enum('FLUTTERWAVE', 'STRIPE', name='payment_status_type_enum', metadata=sa.MetaData(), create_constraint=True), nullable=True))
    op.drop_column('personal_package_payment', 'payment_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_package_payment', sa.Column('payment_status', postgresql.ENUM('FLUTTERWAVE', 'STRIPE', name='payment_status_type_enum'), autoincrement=False, nullable=True))
    op.drop_column('personal_package_payment', 'payment_gateway')
    # ### end Alembic commands ###
