"""Tour Package model modification

Revision ID: 1a8c3e655587
Revises: 4482dfbad6ce
Create Date: 2025-01-15 00:50:45.808369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.model.personal_package_payment import PackagePaymentStatusTypeEnum
from app.model.tour_package import TourPackagePaymentStatusTypeEnum



# revision identifiers, used by Alembic.
revision: str = '1a8c3e655587'
down_revision: Union[str, None] = '4482dfbad6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    PackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    TourPackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    op.add_column('user_tour_packages', sa.Column('user_fullname', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tour_packages', 'user_fullname')
    # ### end Alembic commands ###
    PackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
    TourPackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
