"""Modify region field (name)

Revision ID: 53c741406b42
Revises: a4de070bdb8a
Create Date: 2024-12-14 23:09:59.100384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c741406b42'
down_revision: Union[str, None] = 'a4de070bdb8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'regions', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'regions', type_='unique')
    # ### end Alembic commands ###
