"""Tour Package model modification

Revision ID: 59811528960d
Revises: d86108872d39
Create Date: 2025-01-15 12:03:51.872368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59811528960d'
down_revision: Union[str, None] = 'd86108872d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tour_packages', sa.Column('payment_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='tour_package_payment_status_type_enum', metadata=sa.MetaData(), create_constraint=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tour_packages', 'payment_status')
    # ### end Alembic commands ###
