"""Tour Package model modification

Revision ID: 6525c644e216
Revises: cbde1a3117d0
Create Date: 2025-01-15 00:45:28.049257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.model.personal_package_payment import PackagePaymentStatusTypeEnum
from app.model.tour_package import TourPackagePaymentStatusTypeEnum

# revision identifiers, used by Alembic.
revision: str = '6525c644e216'
down_revision: Union[str, None] = 'cbde1a3117d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    PackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    TourPackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    op.drop_column('user_tour_packages', 'user_fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tour_packages', sa.Column('user_fullname', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
    PackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
    TourPackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
