"""Payment mmodel modification

Revision ID: c7233fdac710
Revises: b0c03e65c055
Create Date: 2025-01-02 18:36:02.045887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.model.personal_package_payment import PackagePaymentStatusTypeEnum
from app.model.tour_package import TourPackagePaymentStatusTypeEnum


# revision identifiers, used by Alembic.
revision: str = 'c7233fdac710'
down_revision: Union[str, None] = 'b0c03e65c055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    PackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    TourPackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)

    op.execute("""
        ALTER TABLE personal_package_payment
        ALTER COLUMN payment_status TYPE payment_status_type_enum
        USING payment_status::payment_status_type_enum
    """)

    op.alter_column('personal_package_payment', 'payment_status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('FLUTTERWAVE', 'STRIPE', name='payment_status_type_enum', metadata=sa.MetaData(), create_constraint=True),
               nullable=True)
    
    op.add_column('tour_packages', sa.Column('active', sa.Boolean(), nullable=True))

    

    op.add_column('tour_packages', sa.Column('payment_status', sa.Enum('PAID', 'NOT_PAID', name='tour_package_payment_status_type_enum', metadata=sa.MetaData(), create_constraint=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_packages', 'payment_status')
    op.drop_column('tour_packages', 'active')
    op.alter_column('personal_package_payment', 'payment_status',
               existing_type=sa.Enum('FLUTTERWAVE', 'STRIPE', name='payment_status_type_enum', metadata=sa.MetaData(), create_constraint=True),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    PackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
    TourPackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
