"""Tour Package model modification

Revision ID: cbde1a3117d0
Revises: 2c7784ff53eb
Create Date: 2025-01-15 00:35:41.689132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.model.personal_package_payment import PackagePaymentStatusTypeEnum
from app.model.tour_package import TourPackagePaymentStatusTypeEnum


# revision identifiers, used by Alembic.
revision: str = 'cbde1a3117d0'
down_revision: Union[str, None] = '2c7784ff53eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    PackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    TourPackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)

    op.create_table('personal_package_payment',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('transaction_ref', sa.String(
                        length=255), nullable=False),
                    sa.Column('payment_ref', sa.String(
                        length=255), nullable=True),
                    sa.Column('user_id', sa.Uuid(), nullable=True),
                    sa.Column('payment_gateway', sa.Enum('FLUTTERWAVE', 'STRIPE', name='payment_status_type_enum',
                                                         metadata=sa.MetaData(), create_constraint=True), nullable=True),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('currency', sa.String(
                        length=255), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('payment_ref'),
                    sa.UniqueConstraint('transaction_ref')
                    )
    op.add_column('user_tour_packages', sa.Column(
        'user_fullname', sa.String(), nullable=False))
    op.add_column('user_tour_packages', sa.Column(
        'user_email', sa.String(), nullable=False))
    op.add_column('user_tour_packages', sa.Column(
        'user_contact', sa.String(), nullable=True))
    op.add_column('user_tour_packages', sa.Column(
        'user_address', sa.String(), nullable=False))
    op.drop_constraint('user_tour_packages_user_id_fkey',
                       'user_tour_packages', type_='foreignkey')
    op.drop_column('user_tour_packages', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tour_packages', sa.Column(
        'user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_tour_packages_user_id_fkey', 'user_tour_packages', 'users', [
                          'user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_tour_packages', 'user_address')
    op.drop_column('user_tour_packages', 'user_contact')
    op.drop_column('user_tour_packages', 'user_email')
    op.drop_column('user_tour_packages', 'user_fullname')
    op.drop_table('personal_package_payment')
    # ### end Alembic commands ###
    PackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
    TourPackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
