"""Tour Package model modification

Revision ID: d86108872d39
Revises: 1a8c3e655587
Create Date: 2025-01-15 12:03:17.983226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd86108872d39'
down_revision: Union[str, None] = '1a8c3e655587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tour_packages', 'payment_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tour_packages', sa.Column('payment_status', postgresql.ENUM('PAID', 'NOT_PAID', name='tour_package_payment_status_type_enum'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
