"""Google verification model

Revision ID: ecd4d02a5551
Revises: 26f8873c8a38
Create Date: 2024-12-13 10:02:11.756937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd4d02a5551'
down_revision: Union[str, None] = '26f8873c8a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_verification', sa.Column('auth_type', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_verification', 'auth_type')
    # ### end Alembic commands ###
