"""Payment mmodel modification

Revision ID: f69f20808d5c
Revises: 9ca8153a5e58
Create Date: 2025-01-02 19:10:44.000050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69f20808d5c'
down_revision: Union[str, None] = '9ca8153a5e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_packages', sa.Column('payment_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tour_packages', 'personal_package_payment', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tour_packages', type_='foreignkey')
    op.drop_column('tour_packages', 'payment_id')
    # ### end Alembic commands ###
