"""Tour Package model modification

Revision ID: fbb4149e7e3b
Revises: 59811528960d
Create Date: 2025-01-15 12:11:55.117959

"""
from typing import Sequence, Union
from app.model.personal_package_payment import PackagePaymentStatusTypeEnum
from app.model.user_tour_package import TourPackagePaymentStatusTypeEnum
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb4149e7e3b'
down_revision: Union[str, None] = '59811528960d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    PackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    TourPackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    # op.add_column('user_tour_packages', sa.Column('payment_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='tour_package_payment_status_type_enum', metadata=sa.MetaData(), create_constraint=True), nullable=True))
    # Add the column to the table
    op.add_column('user_tour_packages', sa.Column(
        'payment_status',
        TourPackagePaymentStatusTypeEnum,
        nullable=True,
        server_default='PENDING'
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tour_packages', 'payment_status')
    # ### end Alembic commands ###
    PackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
    TourPackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
