"""Payment mmodel modification

Revision ID: 0234c0ab058a
Revises: 1452b2197529
Create Date: 2025-01-02 19:02:05.658057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0234c0ab058a'
down_revision: Union[str, None] = '1452b2197529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_package_payment', sa.Column('tour_package_id', sa.Uuid(), nullable=True))
    op.drop_constraint('personal_package_payment_payment_id_fkey', 'personal_package_payment', type_='foreignkey')
    op.create_foreign_key(None, 'personal_package_payment', 'tour_packages', ['tour_package_id'], ['id'], initially='deferred', deferrable=True)
    op.create_foreign_key(None, 'personal_package_payment', 'tour_packages', ['tour_package_id'], ['id'], ondelete='CASCADE')
    op.drop_column('personal_package_payment', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_package_payment', sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'personal_package_payment', type_='foreignkey')
    op.drop_constraint(None, 'personal_package_payment', type_='foreignkey')
    op.create_foreign_key('personal_package_payment_payment_id_fkey', 'personal_package_payment', 'tour_packages', ['payment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('personal_package_payment', 'tour_package_id')
    # ### end Alembic commands ###
