"""Tour Package model modification

Revision ID: 0420f98e6634
Revises: e5cebe2f1762
Create Date: 2025-01-15 12:24:42.304720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# from app.model.personal_package_payment import PackagePaymentStatusTypeEnum
# from app.model.user_tour_package import TourPackagePaymentStatusType, TourPackagePaymentStatusTypeEnum



# revision identifiers, used by Alembic.
revision: str = '0420f98e6634'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # PackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    # TourPackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    op.create_table('user_tour_packages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('user_fullname', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_contact', sa.String(), nullable=True),
    sa.Column('user_address', sa.String(), nullable=False),
    # sa.Column('payment_status', sa.Enum(TourPackagePaymentStatusType, name="tour_package_payment_status_type_enum"), nullable=True),
    sa.Column('tx_ref', sa.String(length=255), nullable=True),
    sa.Column('payment_gateway', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=True),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('accommodation_id', sa.Uuid(), nullable=True),
    sa.Column('no_of_people_attending', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('end_date', sa.Date(), server_default=sa.text("CURRENT_DATE + INTERVAL '3 days'"), nullable=True),
    # sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ),
    # sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_foreign_key(None, 'tour_package_accommodations', 'user_tour_packages', ['tour_package_id'], ['id'], ondelete='CASCADE')
    # op.create_foreign_key(None, 'tour_package_activities', 'user_tour_packages', ['tour_package_id'], ['id'], ondelete='CASCADE')
    # op.create_foreign_key(None, 'tour_package_tour_sites_region', 'user_tour_packages', ['tour_package_id'], ['id'], ondelete='CASCADE')
    # op.create_foreign_key(None, 'tour_package_transportations', 'user_tour_packages', ['tour_package_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tour_package_transportations', type_='foreignkey')
    op.drop_constraint(None, 'tour_package_tour_sites_region', type_='foreignkey')
    op.drop_constraint(None, 'tour_package_activities', type_='foreignkey')
    op.drop_constraint(None, 'tour_package_accommodations', type_='foreignkey')
    op.drop_table('user_tour_packages')
    # PackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
    # TourPackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
