"""Models update

Revision ID: 06f28bc27a92
Revises: f8021263041f
Create Date: 2025-04-26 15:16:42.002457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '06f28bc27a92'
down_revision: Union[str, None] = 'f8021263041f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_packages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('duration_nights', sa.Integer(), nullable=False),
    sa.Column('price_per_person_usd', sa.Float(), nullable=False),
    sa.Column('destinations', sa.Text(), nullable=True),
    sa.Column('accommodation_details', sa.Text(), nullable=True),
    sa.Column('meals_included', sa.Text(), nullable=True),
    sa.Column('transport_info', sa.Text(), nullable=True),
    sa.Column('itinerary', sa.Text(), nullable=True),
    sa.Column('inclusions', sa.Text(), nullable=True),
    sa.Column('package_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_packages')

    # ### end Alembic commands ###
