"""Mod: Destination, Tour Package, Itinerary

Revision ID: 1acaf8a67b3c
Revises: 7b21806882dc
Create Date: 2025-04-29 00:50:40.805791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1acaf8a67b3c'
down_revision: Union[str, None] = '7b21806882dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tour_package_tour_sites_region',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_tour_package_id', sa.Uuid(), nullable=True),
    sa.Column('tour_sites_region_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tour_sites_region_id'], ['tour_sites_region.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_tour_package_id'], ['user_tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tour_package_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_tour_package_id', sa.Uuid(), nullable=True),
    sa.Column('activity_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_tour_package_id'], ['user_tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tour_package_tour_sites_region')
    op.drop_table('tour_package_activities')
    op.add_column('tour_package_transportations', sa.Column('user_tour_package_id', sa.Uuid(), nullable=True))
    op.drop_constraint('tour_package_transportations_tour_package_id_fkey', 'tour_package_transportations', type_='foreignkey')
    op.create_foreign_key(None, 'tour_package_transportations', 'user_tour_packages', ['user_tour_package_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tour_package_transportations', 'tour_package_id')
    op.add_column('user_tour_package_accommodations', sa.Column('user_tour_package_id', sa.Uuid(), nullable=True))
    op.drop_constraint('user_tour_package_accommodations_tour_package_id_fkey', 'user_tour_package_accommodations', type_='foreignkey')
    op.create_foreign_key(None, 'user_tour_package_accommodations', 'user_tour_packages', ['user_tour_package_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_tour_package_accommodations', 'tour_package_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tour_package_accommodations', sa.Column('tour_package_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_tour_package_accommodations', type_='foreignkey')
    op.create_foreign_key('user_tour_package_accommodations_tour_package_id_fkey', 'user_tour_package_accommodations', 'user_tour_packages', ['tour_package_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_tour_package_accommodations', 'user_tour_package_id')
    op.add_column('tour_package_transportations', sa.Column('tour_package_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tour_package_transportations', type_='foreignkey')
    op.create_foreign_key('tour_package_transportations_tour_package_id_fkey', 'tour_package_transportations', 'user_tour_packages', ['tour_package_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tour_package_transportations', 'user_tour_package_id')
    op.create_table('tour_package_activities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tour_package_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name='tour_package_activities_activity_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_package_id'], ['user_tour_packages.id'], name='tour_package_activities_tour_package_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tour_package_activities_pkey')
    )
    op.create_table('tour_package_tour_sites_region',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tour_package_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tour_sites_region_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tour_package_id'], ['user_tour_packages.id'], name='tour_package_tour_sites_region_tour_package_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_sites_region_id'], ['tour_sites_region.id'], name='tour_package_tour_sites_region_tour_sites_region_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tour_package_tour_sites_region_pkey')
    )
    op.drop_table('user_tour_package_activities')
    op.drop_table('user_tour_package_tour_sites_region')
    # ### end Alembic commands ###
