"""Google verification model

Revision ID: 26f8873c8a38
Revises: 29b281e3a085
Create Date: 2024-12-13 09:37:41.654090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f8873c8a38'
down_revision: Union[str, None] = '29b281e3a085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_verification', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_verification', sa.Column('code', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
