"""Initial migration

Revision ID: 28d0f1ca248f
Revises: 63ae87913a11
Create Date: 2025-06-12 19:09:42.364369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28d0f1ca248f'
down_revision: Union[str, None] = '63ae87913a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_packages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('duration_nights', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('price_per_family_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_per_person_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('number_of_travelers', sa.Integer(), nullable=False),
    sa.Column('traveler_adults', sa.Integer(), nullable=False),
    sa.Column('traveler_children', sa.Integer(), nullable=True),
    sa.Column('is_group_pricing', sa.Boolean(), nullable=True),
    sa.Column('accommodation_details', sa.Text(), nullable=True),
    sa.Column('meals_included', sa.Text(), nullable=True),
    sa.Column('transport_info', sa.Text(), nullable=True),
    sa.Column('price_type', sa.Enum('PER_PERSON', 'PER_FAMILY', name='tour_package_price_type_enum'), nullable=True),
    sa.Column('package_type', sa.String(length=50), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=False),
    sa.Column('images_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('termsconditions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('tour_package_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tour_package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('terms_conditions')
    op.create_foreign_key(None, 'destination_tour_packages', 'tour_packages', ['tour_package_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exclusion', 'tour_packages', ['tour_package_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'inclusion', 'tour_packages', ['tour_package_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'itineraries', 'tour_packages', ['tour_package_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itineraries', type_='foreignkey')
    op.drop_constraint(None, 'inclusion', type_='foreignkey')
    op.drop_constraint(None, 'exclusion', type_='foreignkey')
    op.drop_constraint(None, 'destination_tour_packages', type_='foreignkey')
    op.create_table('terms_conditions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.Column('tour_package_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='terms_conditions_pkey')
    )
    op.drop_table('termsconditions')
    op.drop_table('tour_packages')
    # ### end Alembic commands ###
