"""Update: Activity model

Revision ID: 3c5f3a63a8e3
Revises: ff5c7c449d98
Create Date: 2025-02-21 21:41:17.410525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5f3a63a8e3'
down_revision: Union[str, None] = 'ff5c7c449d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activities_tour_sites_region_id'), 'activities', ['tour_sites_region_id'], unique=False)
    op.create_unique_constraint('uq_name_region', 'activities', ['name', 'tour_sites_region_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_name_region', 'activities', type_='unique')
    op.drop_index(op.f('ix_activities_tour_sites_region_id'), table_name='activities')
    # ### end Alembic commands ###
