"""Tour package model

Revision ID: 40f80038baa4
Revises: 45d89e66dc1f
Create Date: 2024-12-20 11:45:50.373725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f80038baa4'
down_revision: Union[str, None] = '45d89e66dc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_packages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('accommodation_id', sa.Uuid(), nullable=True),
    sa.Column('no_of_people_attending', sa.Integer(), nullable=False),
    sa.Column('no_of_nights', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour_package_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tour_package_id', sa.Uuid(), nullable=True),
    sa.Column('activity_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour_package_tour_sites_region',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tour_package_id', sa.Uuid(), nullable=True),
    sa.Column('tour_sites_region_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tour_package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_sites_region_id'], ['tour_sites_region.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour_package_transportations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tour_package_id', sa.Uuid(), nullable=True),
    sa.Column('transportation_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tour_package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transportation_id'], ['transportation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_package_transportations')
    op.drop_table('tour_package_tour_sites_region')
    op.drop_table('tour_package_activities')
    op.drop_table('tour_packages')
    # ### end Alembic commands ###
