"""Tour package and package payment model modification

Revision ID: 5a66e185eae3
Revises: 4056538a77d1
Create Date: 2025-01-20 11:28:49.062806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.model.personal_package_payment import PackagePaymentStatusTypeEnum
from app.model.tour_package import TourPackagePaymentStatusType, TourPackagePaymentStatusTypeEnum

# revision identifiers, used by Alembic.
revision: str = '5a66e185eae3'
down_revision: Union[str, None] = '4056538a77d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    PackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    TourPackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    op.drop_constraint('personal_package_payment_tour_package_id_fkey1', 'personal_package_payment', type_='foreignkey')
    op.drop_constraint('user_tour_packages_payment_id_fkey1', 'user_tour_packages', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_tour_packages_payment_id_fkey1', 'user_tour_packages', 'personal_package_payment', ['payment_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('personal_package_payment_tour_package_id_fkey1', 'personal_package_payment', 'user_tour_packages', ['tour_package_id'], ['id'], initially='DEFERRED', deferrable=True)
    PackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
    TourPackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
