"""Mod: Destination, Tour Package, Itinerary

Revision ID: 5b680bcf53aa
Revises: 61fb09587e19
Create Date: 2025-04-29 01:26:34.184011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b680bcf53aa'
down_revision: Union[str, None] = '61fb09587e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_packages', sa.Column('exclusions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_packages', 'exclusions')
    # ### end Alembic commands ###
