"""Models update

Revision ID: 660f7f2411bf
Revises: 06f28bc27a92
Create Date: 2025-04-26 15:44:23.097092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# from app.model.personal_package_payment import PackagePaymentStatusTypeEnum
# from app.model.user_tour_package import TourPackagePaymentStatusTypeEnum


# revision identifiers, used by Alembic.
revision: str = '660f7f2411bf'
down_revision: Union[str, None] = '06f28bc27a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tour_package_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_tour_package_id', sa.Uuid(), nullable=True),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['user_payment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_tour_package_id'], ['user_tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # PackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    # TourPackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tour_package_payments')
    # PackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
    # TourPackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
