"""Tour package and package payment model modification

Revision ID: 6ed9d53eb55c
Revises: 774fd8aa939a
Create Date: 2025-01-20 10:26:12.120110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6ed9d53eb55c'
down_revision: Union[str, None] = '774fd8aa939a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tour_packages', sa.Column('payment_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user_tour_packages', 'personal_package_payment', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tour_packages', type_='foreignkey')
    op.drop_column('user_tour_packages', 'payment_id')
    # ### end Alembic commands ###
