"""New model: Itinerary model

Revision ID: 730d7fd3ea50
Revises: eef9e09ed72b
Create Date: 2025-04-28 20:27:11.218620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730d7fd3ea50'
down_revision: Union[str, None] = 'eef9e09ed72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itineraries', sa.Column('title', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itineraries', 'title')
    # ### end Alembic commands ###
