"""Mod: Destination, Tour Package, Itinerary

Revision ID: 749034036131
Revises: f0b2f976a904
Create Date: 2025-04-29 07:58:41.478028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749034036131'
down_revision: Union[str, None] = 'f0b2f976a904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_packages', sa.Column('terms_conditions', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_packages', 'terms_conditions')
    # ### end Alembic commands ###
