"""Tour package model modification

Revision ID: 774fd8aa939a
Revises: dc23ed694d85
Create Date: 2025-01-19 20:35:47.725983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '774fd8aa939a'
down_revision: Union[str, None] = 'dc23ed694d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_package_payment', sa.Column('tour_package_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_package_payment', 'tour_package_id')
    # ### end Alembic commands ###
