"""Mod: Destination, Tour Package, Itinerary

Revision ID: 7b21806882dc
Revises: 730d7fd3ea50
Create Date: 2025-04-29 00:06:29.157104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b21806882dc'
down_revision: Union[str, None] = '730d7fd3ea50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_packages', 'destinations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_packages', sa.Column('destinations', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
