"""New Table: Exclusion

Revision ID: 85338b572c8b
Revises: e3eaf498d9db
Create Date: 2025-04-29 11:39:46.395571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85338b572c8b'
down_revision: Union[str, None] = 'e3eaf498d9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exclusion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('tour_package_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tour_package_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('tour_packages', 'exclusions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_packages', sa.Column('exclusions', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('exclusion')
    # ### end Alembic commands ###
