"""Tour package model update

Revision ID: 8c873b94b996
Revises: 40f80038baa4
Create Date: 2024-12-22 02:14:16.710893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c873b94b996'
down_revision: Union[str, None] = '40f80038baa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_packages', 'no_of_nights')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_packages', sa.Column('no_of_nights', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
