"""User Payment model

Revision ID: 91c332abba26
Revises: 3c5f3a63a8e3
Create Date: 2025-04-20 22:12:10.724444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '91c332abba26'
down_revision: Union[str, None] = '3c5f3a63a8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_payment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('tx_ref', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user_tour_packages', 'payment_gateway')
    op.drop_column('user_tour_packages', 'currency')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tour_packages', sa.Column('currency', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_tour_packages', sa.Column('payment_gateway', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('user_payment')

    # ### end Alembic commands ###
