"""Payment mmodel modification

Revision ID: 9bee3ae3f962
Revises: 0234c0ab058a
Create Date: 2025-01-02 19:05:49.752854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bee3ae3f962'
down_revision: Union[str, None] = '0234c0ab058a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tour_packages_payment_id_fkey', 'tour_packages', type_='foreignkey')
    op.drop_column('tour_packages', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_packages', sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('tour_packages_payment_id_fkey', 'tour_packages', 'personal_package_payment', ['payment_id'], ['id'])
    # ### end Alembic commands ###
