"""Payment mmodel modification

Revision ID: b0c03e65c055
Revises: 171744168348
Create Date: 2025-01-02 17:58:46.671367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0c03e65c055'
down_revision: Union[str, None] = '171744168348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_package_payment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('transaction_ref', sa.String(length=255), nullable=False),
    sa.Column('payment_ref', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('payment_status', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=255), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['tour_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_ref'),
    sa.UniqueConstraint('transaction_ref')
    )
    op.drop_table('payment')
    op.add_column('tour_packages', sa.Column('payment_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tour_packages', 'personal_package_payment', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tour_packages', type_='foreignkey')
    op.drop_column('tour_packages', 'payment_id')
    op.create_table('payment',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('transaction_ref', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('payment_ref', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payment_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='payment_pkey'),
    sa.UniqueConstraint('payment_ref', name='payment_payment_ref_key'),
    sa.UniqueConstraint('transaction_ref', name='payment_transaction_ref_key')
    )
    op.drop_table('personal_package_payment')
    # ### end Alembic commands ###
