"""New model: Itinerary model

Revision ID: cfc6091e0d39
Revises: 3ea54d3887b7
Create Date: 2025-04-28 20:07:04.538029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc6091e0d39'
down_revision: Union[str, None] = '3ea54d3887b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_packages', 'itinerary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_packages', sa.Column('itinerary', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
