"""Models update

Revision ID: d4063f4121b3
Revises: e3b31ad2a337
Create Date: 2025-04-26 16:49:14.183843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4063f4121b3'
down_revision: Union[str, None] = 'e3b31ad2a337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tour_package_accommodations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tour_package_id', sa.Uuid(), nullable=True),
    sa.Column('accommodation_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_package_id'], ['user_tour_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tour_package_accommodations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_package_accommodations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tour_package_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('accommodation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], name='tour_package_accommodations_accommodation_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_package_id'], ['user_tour_packages.id'], name='tour_package_accommodations_tour_package_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tour_package_accommodations_pkey')
    )
    op.drop_table('user_tour_package_accommodations')
    # ### end Alembic commands ###
