"""Tour package and package payment model modification

Revision ID: daf371424620
Revises: 5a66e185eae3
Create Date: 2025-01-20 11:30:46.725895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.model.personal_package_payment import PackagePaymentStatusTypeEnum
from app.model.tour_package import TourPackagePaymentStatusType, TourPackagePaymentStatusTypeEnum

# revision identifiers, used by Alembic.
revision: str = 'daf371424620'
down_revision: Union[str, None] = '5a66e185eae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    PackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    TourPackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    op.drop_constraint('user_tour_packages_payment_id_fkey', 'user_tour_packages', type_='foreignkey')
    op.drop_column('user_tour_packages', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tour_packages', sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_tour_packages_payment_id_fkey', 'user_tour_packages', 'personal_package_payment', ['payment_id'], ['id'])
    PackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
    TourPackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
