"""Tour package model modification

Revision ID: dc23ed694d85
Revises: f6fd367d22ae
Create Date: 2025-01-19 10:48:45.229668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc23ed694d85'
down_revision: Union[str, None] = 'f6fd367d22ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('user_tour_packages', sa.Column('user_id', sa.Uuid(), nullable=True))
    # op.create_foreign_key(None, 'user_tour_packages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_tour_packages', 'user_contact')
    op.drop_column('user_tour_packages', 'user_email')
    op.drop_column('user_tour_packages', 'user_fullname')
    op.drop_column('user_tour_packages', 'user_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tour_packages', sa.Column('user_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_tour_packages', sa.Column('user_fullname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_tour_packages', sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_tour_packages', sa.Column('user_contact', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_tour_packages', type_='foreignkey')
    op.drop_column('user_tour_packages', 'user_id')
    # ### end Alembic commands ###
