"""Models update

Revision ID: e3b31ad2a337
Revises: 660f7f2411bf
Create Date: 2025-04-26 16:28:36.231460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3b31ad2a337'
down_revision: Union[str, None] = '660f7f2411bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_package_payment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_package_payment',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('transaction_ref', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('payment_ref', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('payment_gateway', postgresql.ENUM('FLUTTERWAVE', 'STRIPE', name='payment_status_type_enum'), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tour_package_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tour_package_id'], ['user_tour_packages.id'], name='personal_package_payment_tour_package_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='personal_package_payment_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='personal_package_payment_pkey'),
    sa.UniqueConstraint('payment_ref', name='personal_package_payment_payment_ref_key'),
    sa.UniqueConstraint('transaction_ref', name='personal_package_payment_transaction_ref_key')
    )
    # ### end Alembic commands ###
