"""Update: Activity model

Revision ID: e8d395e55c84
Revises: a627e30a991b
Create Date: 2025-02-19 09:39:15.653849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.model.personal_package_payment import PackagePaymentStatusTypeEnum
from app.model.tour_package import TourPackagePaymentStatusType, TourPackagePaymentStatusTypeEnum

# revision identifiers, used by Alembic.
revision: str = 'e8d395e55c84'
down_revision: Union[str, None] = 'a627e30a991b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    PackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    TourPackagePaymentStatusTypeEnum.create(op.get_bind(), checkfirst=True)
    op.add_column('activities', sa.Column(
        'tour_sites_region_id', sa.Uuid(), nullable=True))
    op.drop_constraint('activities_region_id_fkey',
                       'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'tour_sites_region', [
                          'tour_sites_region_id'], ['id'], ondelete='CASCADE')
    op.drop_column('activities', 'region_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column(
        'region_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key('activities_region_id_fkey', 'activities', 'regions', [
                          'region_id'], ['id'], ondelete='CASCADE')
    op.drop_column('activities', 'tour_sites_region_id')
    PackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
    TourPackagePaymentStatusTypeEnum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
