"""Mod: Destination, Tour Package, Itinerary

Revision ID: f0b2f976a904
Revises: 5b680bcf53aa
Create Date: 2025-04-29 01:36:26.293508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b2f976a904'
down_revision: Union[str, None] = '5b680bcf53aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_packages', sa.Column('thumbnail_url', sa.String(length=255), nullable=False))
    op.add_column('tour_packages', sa.Column('images_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_packages', 'images_url')
    op.drop_column('tour_packages', 'thumbnail_url')
    # ### end Alembic commands ###
