"""Tour Package model modification

Revision ID: f6fd367d22ae
Revises: 0420f98e6634
Create Date: 2025-01-15 12:34:42.097742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6fd367d22ae'
down_revision: Union[str, None] = '0420f98e6634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tour_packages', 'user_address',
                    existing_type=sa.VARCHAR(),
                    nullable=True),
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tour_packages', 'user_address',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###
